// This file is auto-generated by ./bin/rails stimulus:manifest:update
// Run that command whenever you add a new controller or create them with
// ./bin/rails generate stimulus controllerName

import { application } from "./application"

import AppointmentController from "./appointment_controller"
application.register("appointment", AppointmentController)

import AppointmentRegisterController from "./appointment_register_controller"
application.register("appointment-register", AppointmentRegisterController)

import HelloController from "./hello_controller"
application.register("hello", HelloController)

import NavbarTrackerController from "./navbar_tracker_controller"
application.register("navbar-tracker", NavbarTrackerController)

import NestedFormController from "./nested_form_controller"
application.register("nested-form", NestedFormController)

import PushController from "./push_controller"
application.register("push", PushController)

import TimeZoneController from "./time_zone_controller"
application.register("time-zone", TimeZoneController)
