# version: '3.8'

services:
  db:
    image: postgres:14.2-alpine
    container_name: postgres_db
    restart: unless-stopped
    volumes:
      - postgres_data:/var/lib/postgresql/data
    environment:
      POSTGRES_DB: medicine_record
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
    networks:
      - app_network
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 5s
      retries: 5

  redis:
    image: redis/redis-stack-server:7.2.0-v6
    container_name: redis_cache
    restart: unless-stopped
    ports:
      - 6379:6379
    healthcheck:
      test: ["CMD", "redis-cli", "--raw", "ping"]
      interval: 10s
      timeout: 5s
      retries: 3
    volumes:
      - redis_data:/data
    networks:
      - app_network

  web:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: rails_app
    command: "foreman start -f Procfile.dev"
    volumes:
      - .:/app:delegated
      - /app/node_modules
    depends_on:
      db:
        condition: service_healthy
      redis:
        condition: service_healthy
    environment:
      DATABASE_URL: postgres://postgres:password@db:5432/medicine_record
      REDIS_URL: redis://redis:6379/0
      CLOUD_NAME: ${CLOUD_NAME}
      API_KEY: ${API_KEY}
      API_SECRET: ${API_SECRET}
      URL: ${URL}
    ports:
      - "3000:3000"
    networks:
      - app_network

volumes:
  postgres_data:
  redis_data:

networks:
  app_network:
    driver: bridge
