---
development:
  cloud_name: dgimwjugr
  api_key: '178121197876222'
  api_secret: aDIsdSBMaaLmkagYo8wAqq4kGWE
  enhance_image_tag: true
  static_file_support: false
production:
  cloud_name: dgimwjugr
  api_key: '178121197876222'
  api_secret: aDIsdSBMaaLmkagYo8wAqq4kGWE
  enhance_image_tag: true
  static_file_support: true
test:
  cloud_name: dgimwjugr
  api_key: '178121197876222'
  api_secret: aDIsdSBMaaLmkagYo8wAqq4kGWE
  enhance_image_tag: true
  static_file_support: false
