# config/sidekiq.yml

:scheduler:
  :schedule:
    hello_world:
      cron: "* * * * *"
      class: "HelloWorldSchedular"
      queue: "default"
    expire_date:
      cron: "0 0 * * *"
      class: "ExpireDateSchedular"
      queue: "default"